import type { Lang } from './i18n.svelte';
import type { PhaseKey } from './moon';

/** Copy for the generated pages (moon phases, birth years, star pages). */
export const PT = {
  en: {
    phase: {
      new: 'New Moon', waxingCrescent: 'Waxing crescent', firstQuarter: 'First quarter', waxingGibbous: 'Waxing gibbous',
      full: 'Full Moon', waningGibbous: 'Waning gibbous', lastQuarter: 'Last quarter', waningCrescent: 'Waning crescent',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    timeZoneNote: 'Times are in UTC (Greenwich).',
    moonTz: 'UTC',
    /** Latitude for "when can I see it" on star pages (negative: south). */
    visibilityLat: 42,

    moonHubTitle: 'Moon Phase on Any Date: What Was the Moon the Day You Were Born? | Sky of Your Day',
    moonHubDescription: 'Look up the Moon’s phase on any date since 1930: full moons, new moons and a daily calendar for every month, with exact times.',
    moonHubH1: 'What was the Moon like on the day you were born?',
    moonHubLead: 'Pick a date to see the Moon’s phase that day, how much of it was lit, and when the nearest full and new moons fell. Every month since 1930 has its own calendar.',
    lookUp: 'Show the Moon',
    dateLabel: 'Date',
    yearsHeading: 'Browse by year',

    moonYearTitle: (y: number) => `Moon Phases ${y}: Every Full Moon and New Moon | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `All ${fulls} full moons and every new moon of ${y}, with dates and times, and a daily Moon calendar for each month.`,
    moonYearH1: (y: number) => `Moon phases in ${y}`,
    moonYearLead: (y: number, fulls: number) => `There were ${fulls} full moons in ${y}. Choose a month for the Moon’s phase on every day.`,
    blueMoon: (month: string) => `${month} had two full moons: the second is what is called a blue moon.`,
    colMonth: 'Month',
    colFull: 'Full Moon',
    colNew: 'New Moon',

    moonMonthTitle: (m: string, y: number) => `Moon Phases ${m} ${y}: Full Moon, New Moon & Daily Calendar | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Full Moon on ${full}. ` : ''}${nw ? `New Moon on ${nw}. ` : ''}The Moon’s phase and how much of it was lit on every day of ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Moon phases in ${m} ${y}`,
    keyMoments: 'Main phases',
    litShare: (p: number) => `${p}% lit`,
    at: (date: string, time: string) => `${date} at ${time}`,
    bornThisMonth: 'Born this month?',
    bornCta: 'Find the star whose light left it the day you were born, and see where it is tonight.',
    posterCta: 'Or make a free poster of the real sky of that night, with the Moon in its phase.',
    findStar: 'Find your star',
    makePoster: 'Make the poster',
    prev: 'Previous',
    next: 'Next',
    allYears: 'All years',

    bornHubTitle: 'The Star of Your Birth Year: Whose Light Left the Year You Were Born | Sky of Your Day',
    bornHubDescription: 'For every birth year since 1930, the stars whose light set out that year and is reaching Earth now. Find yours.',
    bornHubH1: 'The star of your birth year',
    bornHubLead: 'Light from a star 40 light years away set out 40 years ago. So every birth year has its stars: the ones whose light left them that year and is arriving now.',
    bornTitle: (y: number) => `Born in ${y}? The Star Whose Light Left the Year You Were Born | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `Light that set out in ${y} is reaching Earth now from stars about ${ly} light years away, like ${star}. See the star for each month of ${y} and where to find it.`,
    bornH1: (y: number) => `Born in ${y}: your star`,
    bornLead: (y: number, ly: string) =>
      `Light that set out in ${y} is reaching Earth right now from stars about ${ly} light years away. Here is the star for each month of ${y}: the one whose light left it then and is arriving about now.`,
    colStar: 'Star',
    colDistance: 'Distance',
    colSeen: 'How to see it',
    colConstellation: 'Constellation',
    lightYears: (n: string) => `${n} light years`,
    exactDate: 'For the exact star of your birthday, and where to look for it tonight:',
    moonOfYear: (y: number) => `The Moon in ${y}`,

    starsHubTitle: 'Named Stars: Where to Find Them, Distance and Facts | Sky of Your Day',
    starsHubDescription: 'Every star with an official name: where it is in the sky, how far away, when you can see it and when the light you see tonight left it.',
    starsHubH1: 'Stars with a name',
    starsHubLead: 'The International Astronomical Union has given official names to a few hundred stars. For each: where to find it, how far away it is, and when the light you see tonight set out.',
    brightestHeading: 'The brightest',
    allHeading: 'All named stars',

    starTitle: (name: string) => `${name}: Where to Find It, Distance and Facts | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} is ${kind}${dist}. Where to find it in the sky, when you can see it and how bright it is.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, ${ly} light years away: the light you see tonight left it around ${year}` : `, ${ly} light years away`),
    whereHeading: 'Where to find it',
    factsHeading: 'What it’s like',
    lightLeft: (year: number) => `The light you see from it tonight left it around ${year}.`,
    lightLeftAncient: (years: string) => `The light you see from it tonight set out about ${years} years ago.`,
    unknownDistance: 'Its distance is not known precisely.',
    fromLatitudes: 'From mid-northern latitudes, such as New York, Rome or Tokyo,',
    bestMonths: (list: string) => `it is best seen in the evening sky in ${list}.`,
    circumpolar: 'it never sets: it circles the pole all night, all year.',
    neverVisible: 'it never rises: it belongs to the southern sky.',
    lowAlways: 'it only ever stays low over the southern horizon.',
    birthYearLink: (year: number) => `It is the star of people born around ${year}: the light that left it then is reaching Earth now.`,
    sameConstellation: (con: string) => `Other named stars in ${con}`,
    magnitude: (m: string) => `Apparent magnitude ${m}.`,
  },
  es: {
    phase: {
      new: 'Luna nueva', waxingCrescent: 'Luna creciente', firstQuarter: 'Cuarto creciente', waxingGibbous: 'Gibosa creciente',
      full: 'Luna llena', waningGibbous: 'Gibosa menguante', lastQuarter: 'Cuarto menguante', waningCrescent: 'Luna menguante',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    timeZoneNote: 'Las horas están en UTC (hora universal).',
    moonTz: 'UTC',
    visibilityLat: 42,

    moonHubTitle: '¿Qué luna había el día que naciste? Fases lunares de cualquier fecha | Sky of Your Day',
    moonHubDescription: 'Consulta la fase de la Luna en cualquier fecha desde 1930: lunas llenas, lunas nuevas y el calendario lunar de cada mes, con las horas exactas.',
    moonHubH1: '¿Qué luna había el día de tu nacimiento?',
    moonHubLead: 'Elige una fecha para ver la fase de la Luna ese día, qué parte estaba iluminada y cuándo cayeron la luna llena y la luna nueva más cercanas. Cada mes desde 1930 tiene su calendario.',
    lookUp: 'Ver la Luna',
    dateLabel: 'Fecha',
    yearsHeading: 'Por años',

    moonYearTitle: (y: number) => `Fases lunares ${y}: todas las lunas llenas y lunas nuevas | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Las ${fulls} lunas llenas y todas las lunas nuevas de ${y}, con fecha y hora, y el calendario lunar día a día de cada mes.`,
    moonYearH1: (y: number) => `Fases lunares de ${y}`,
    moonYearLead: (y: number, fulls: number) => `En ${y} hubo ${fulls} lunas llenas. Elige un mes para ver la fase de la Luna día a día.`,
    blueMoon: (month: string) => `En ${month} hubo dos lunas llenas: la segunda es la que se llama “luna azul”.`,
    colMonth: 'Mes',
    colFull: 'Luna llena',
    colNew: 'Luna nueva',

    moonMonthTitle: (m: string, y: number) => `Fases lunares ${m} ${y}: luna llena, luna nueva y calendario | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Luna llena el ${full}. ` : ''}${nw ? `Luna nueva el ${nw}. ` : ''}La fase de la Luna y qué parte estaba iluminada cada día de ${m} de ${y}.`,
    moonMonthH1: (m: string, y: number) => `Fases lunares de ${m} de ${y}`,
    keyMoments: 'Las fases principales',
    litShare: (p: number) => `iluminada al ${p}%`,
    at: (date: string, time: string) => `${date} a las ${time}`,
    bornThisMonth: '¿Tu nacimiento es de este mes?',
    bornCta: 'Descubre la estrella cuya luz salió el día de tu nacimiento y dónde está esta noche.',
    posterCta: 'O crea gratis el póster del cielo real de aquella noche, con la Luna en su fase.',
    findStar: 'Encuentra tu estrella',
    makePoster: 'Crear el póster',
    prev: 'Anterior',
    next: 'Siguiente',
    allYears: 'Todos los años',

    bornHubTitle: 'La estrella de tu año de nacimiento: la luz que salió ese año llega ahora | Sky of Your Day',
    bornHubDescription: 'Para cada año de nacimiento desde 1930, las estrellas cuya luz salió ese año y está llegando ahora a la Tierra. Encuentra la tuya.',
    bornHubH1: 'La estrella de tu año de nacimiento',
    bornHubLead: 'La luz de una estrella a 40 años luz salió hace 40 años. Así que cada año de nacimiento tiene sus estrellas: aquellas cuya luz salió entonces y está llegando ahora.',
    bornTitle: (y: number) => `Nacidos en ${y}: la estrella cuya luz salió ese año | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `La luz que salió en ${y} está llegando ahora a la Tierra desde estrellas a unos ${ly} años luz, como ${star}. La estrella de cada mes de ${y} y dónde encontrarla.`,
    bornH1: (y: number) => `Nacidos en ${y}: vuestra estrella`,
    bornLead: (y: number, ly: string) =>
      `La luz que salió en ${y} está llegando a la Tierra justo ahora desde estrellas a unos ${ly} años luz. Esta es la estrella de cada mes de ${y}: aquella cuya luz salió entonces y llega más o menos hoy.`,
    colStar: 'Estrella',
    colDistance: 'Distancia',
    colSeen: 'Cómo verla',
    colConstellation: 'Constelación',
    lightYears: (n: string) => `${n} años luz`,
    exactDate: 'Para la estrella exacta de tu cumpleaños, y para saber dónde mirarla esta noche:',
    moonOfYear: (y: number) => `La Luna en ${y}`,

    starsHubTitle: 'Las estrellas con nombre: dónde encontrarlas, distancia y curiosidades | Sky of Your Day',
    starsHubDescription: 'Todas las estrellas con nombre oficial: dónde están en el cielo, a qué distancia, cuándo se ven y cuándo salió la luz que ves esta noche.',
    starsHubH1: 'Las estrellas con nombre',
    starsHubLead: 'La Unión Astronómica Internacional ha dado nombre oficial a unos cientos de estrellas. Para cada una: dónde encontrarla, a qué distancia está y cuándo salió la luz que ves esta noche.',
    brightestHeading: 'Las más brillantes',
    allHeading: 'Todas las estrellas con nombre',

    starTitle: (name: string) => `${name}: dónde encontrarla, distancia y curiosidades | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} es ${kind}${dist}. Dónde encontrarla en el cielo, cuándo se ve y cuánto brilla.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, a ${ly} años luz: la luz que ves esta noche salió hacia ${year}` : `, a ${ly} años luz`),
    whereHeading: 'Dónde encontrarla',
    factsHeading: 'Cómo es',
    lightLeft: (year: number) => `La luz que ves de ella esta noche salió hacia ${year}.`,
    lightLeftAncient: (years: string) => `La luz que ves de ella esta noche salió hace unos ${years} años.`,
    unknownDistance: 'Su distancia no se conoce con precisión.',
    fromLatitudes: 'Desde latitudes medias del norte, como Madrid, Ciudad de México o Nueva York,',
    bestMonths: (list: string) => `se ve mejor al anochecer en ${list}.`,
    circumpolar: 'nunca se pone: gira alrededor del polo toda la noche, todo el año.',
    neverVisible: 'nunca sale: pertenece al cielo austral.',
    lowAlways: 'siempre se queda baja sobre el horizonte sur.',
    birthYearLink: (year: number) => `Es la estrella de los nacidos hacia ${year}: la luz que salió entonces está llegando ahora a la Tierra.`,
    sameConstellation: (con: string) => `Otras estrellas con nombre en la constelación ${con}`,
    magnitude: (m: string) => `Magnitud aparente ${m}.`,
  },
  it: {
    phase: {
      new: 'Luna nuova', waxingCrescent: 'Luna crescente', firstQuarter: 'Primo quarto', waxingGibbous: 'Gibbosa crescente',
      full: 'Luna piena', waningGibbous: 'Gibbosa calante', lastQuarter: 'Ultimo quarto', waningCrescent: 'Luna calante',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'],
    timeZoneNote: 'Gli orari sono in ora italiana, con l’ora legale quando era in vigore.',
    moonTz: 'Europe/Rome',
    visibilityLat: 42,

    moonHubTitle: 'Che luna c’era il giorno della tua nascita? Fasi lunari di ogni data | Sky of Your Day',
    moonHubDescription: 'Scopri la fase della Luna in qualsiasi data dal 1930: lune piene, lune nuove e calendario lunare di ogni mese, con gli orari esatti.',
    moonHubH1: 'Che luna c’era il giorno della tua nascita?',
    moonHubLead: 'Scegli una data per vedere la fase della Luna quel giorno, quanta parte era illuminata e quando sono cadute la luna piena e la luna nuova più vicine. Ogni mese dal 1930 ha il suo calendario.',
    lookUp: 'Mostra la Luna',
    dateLabel: 'Data',
    yearsHeading: 'Sfoglia per anno',

    moonYearTitle: (y: number) => `Fasi lunari ${y}: tutte le lune piene e le lune nuove | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Le ${fulls} lune piene e tutte le lune nuove del ${y}, con data e ora, e il calendario lunare giorno per giorno di ogni mese.`,
    moonYearH1: (y: number) => `Fasi lunari del ${y}`,
    moonYearLead: (y: number, fulls: number) => `Nel ${y} ci sono state ${fulls} lune piene. Scegli un mese per vedere la fase della Luna giorno per giorno.`,
    blueMoon: (month: string) => `A ${month} ci sono state due lune piene: la seconda è quella che si chiama “luna blu”.`,
    colMonth: 'Mese',
    colFull: 'Luna piena',
    colNew: 'Luna nuova',

    moonMonthTitle: (m: string, y: number) => `Fasi lunari ${m} ${y}: luna piena, luna nuova e calendario | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Luna piena il ${full}. ` : ''}${nw ? `Luna nuova il ${nw}. ` : ''}La fase della Luna e quanta parte era illuminata in ogni giorno di ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Fasi lunari di ${m} ${y}`,
    keyMoments: 'Le fasi principali',
    litShare: (p: number) => `illuminata al ${p}%`,
    at: (date: string, time: string) => `${date} alle ${time}`,
    bornThisMonth: 'La tua nascita è di questo mese?',
    bornCta: 'Scopri la stella la cui luce è partita il giorno della tua nascita e dove si trova stasera.',
    posterCta: 'Oppure crea gratis il poster del cielo vero di quella notte, con la Luna nella sua fase.',
    findStar: 'Trova la tua stella',
    makePoster: 'Crea il poster',
    prev: 'Precedente',
    next: 'Successivo',
    allYears: 'Tutti gli anni',

    bornHubTitle: 'La stella del tuo anno di nascita: la luce partita quell’anno arriva adesso | Sky of Your Day',
    bornHubDescription: 'Per ogni anno di nascita dal 1930, le stelle la cui luce è partita quell’anno e arriva sulla Terra adesso. Trova la tua.',
    bornHubH1: 'La stella del tuo anno di nascita',
    bornHubLead: 'La luce di una stella lontana 40 anni luce è partita 40 anni fa. Ogni anno di nascita ha quindi le sue stelle: quelle la cui luce è partita allora e arriva adesso.',
    bornTitle: (y: number) => `Nati nel ${y}: la stella la cui luce è partita quell’anno | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `La luce partita nel ${y} arriva sulla Terra adesso da stelle lontane circa ${ly} anni luce, come ${star}. La stella di ogni mese del ${y} e dove trovarla.`,
    bornH1: (y: number) => `Nati nel ${y}: la vostra stella`,
    bornLead: (y: number, ly: string) =>
      `La luce partita nel ${y} arriva sulla Terra proprio adesso da stelle lontane circa ${ly} anni luce. Ecco la stella di ogni mese del ${y}: quella la cui luce è partita allora e arriva più o meno oggi.`,
    colStar: 'Stella',
    colDistance: 'Distanza',
    colSeen: 'Come vederla',
    colConstellation: 'Costellazione',
    lightYears: (n: string) => `${n} anni luce`,
    exactDate: 'Per la stella esatta del tuo compleanno, e per sapere dove guardarla stasera:',
    moonOfYear: (y: number) => `La Luna nel ${y}`,

    starsHubTitle: 'Le stelle con un nome: dove trovarle, distanza e curiosità | Sky of Your Day',
    starsHubDescription: 'Tutte le stelle con un nome ufficiale: dove si trovano in cielo, quanto distano, quando si vedono e quando è partita la luce che vedi stasera.',
    starsHubH1: 'Le stelle con un nome',
    starsHubLead: 'L’Unione Astronomica Internazionale ha dato un nome ufficiale ad alcune centinaia di stelle. Per ognuna: dove trovarla, quanto dista e quando è partita la luce che vedi stasera.',
    brightestHeading: 'Le più luminose',
    allHeading: 'Tutte le stelle con un nome',

    starTitle: (name: string) => `${name}: dove si trova, distanza e curiosità | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} è ${kind}${dist}. Dove trovarla in cielo, quando si vede e quanto è luminosa.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, a ${ly} anni luce: la luce che vedi stasera è partita intorno al ${year}` : `, a ${ly} anni luce`),
    whereHeading: 'Dove trovarla',
    factsHeading: 'Com’è fatta',
    lightLeft: (year: number) => `La luce che vedi stasera è partita da lei intorno al ${year}.`,
    lightLeftAncient: (years: string) => `La luce che vedi stasera è partita da lei circa ${years} anni fa.`,
    unknownDistance: 'La sua distanza non è nota con precisione.',
    fromLatitudes: 'Dall’Italia',
    bestMonths: (list: string) => `si vede meglio la sera nei mesi di ${list}.`,
    circumpolar: 'non tramonta mai: gira intorno al polo tutta la notte, tutto l’anno.',
    neverVisible: 'non sorge mai: appartiene al cielo australe.',
    lowAlways: 'resta sempre bassa sull’orizzonte sud.',
    birthYearLink: (year: number) => `È la stella dei nati intorno al ${year}: la luce partita allora arriva sulla Terra adesso.`,
    sameConstellation: (con: string) => `Altre stelle con un nome nella costellazione ${con}`,
    magnitude: (m: string) => `Magnitudine apparente ${m}.`,
  },
  de: {
    phase: {
      new: 'Neumond', waxingCrescent: 'Zunehmende Sichel', firstQuarter: 'Erstes Viertel', waxingGibbous: 'Zunehmender Mond',
      full: 'Vollmond', waningGibbous: 'Abnehmender Mond', lastQuarter: 'Letztes Viertel', waningCrescent: 'Abnehmende Sichel',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    timeZoneNote: 'Die Uhrzeiten sind in deutscher Zeit angegeben, mit Sommerzeit, wenn sie galt.',
    moonTz: 'Europe/Berlin',
    visibilityLat: 50,

    moonHubTitle: 'Welcher Mond war an deinem Geburtstag? Mondphasen für jedes Datum | Sky of Your Day',
    moonHubDescription: 'Finde die Mondphase an jedem Datum seit 1930: Vollmonde, Neumonde und ein Mondkalender für jeden Monat, mit genauen Uhrzeiten.',
    moonHubH1: 'Welcher Mond war an deinem Geburtstag?',
    moonHubLead: 'Wähle ein Datum und sieh die Mondphase an diesem Tag, wie viel von ihm beleuchtet war und wann der nächste Vollmond und Neumond waren. Jeder Monat seit 1930 hat seinen Kalender.',
    lookUp: 'Mond anzeigen',
    dateLabel: 'Datum',
    yearsHeading: 'Nach Jahren',

    moonYearTitle: (y: number) => `Mondphasen ${y}: alle Vollmonde und Neumonde | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Alle ${fulls} Vollmonde und alle Neumonde ${y}, mit Datum und Uhrzeit, und ein Mondkalender für jeden Tag jedes Monats.`,
    moonYearH1: (y: number) => `Mondphasen ${y}`,
    moonYearLead: (y: number, fulls: number) => `${y} gab es ${fulls} Vollmonde. Wähle einen Monat für die Mondphase an jedem Tag.`,
    blueMoon: (month: string) => `Im ${month} gab es zwei Vollmonde: den zweiten nennt man „Blue Moon“.`,
    colMonth: 'Monat',
    colFull: 'Vollmond',
    colNew: 'Neumond',

    moonMonthTitle: (m: string, y: number) => `Mondphasen ${m} ${y}: Vollmond, Neumond und Mondkalender | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Vollmond am ${full}. ` : ''}${nw ? `Neumond am ${nw}. ` : ''}Die Mondphase und wie viel vom Mond beleuchtet war, an jedem Tag im ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Mondphasen im ${m} ${y}`,
    keyMoments: 'Die wichtigsten Phasen',
    litShare: (p: number) => `zu ${p} % beleuchtet`,
    at: (date: string, time: string) => `${date} um ${time} Uhr`,
    bornThisMonth: 'In diesem Monat geboren?',
    bornCta: 'Finde den Stern, dessen Licht an deinem Geburtstag aufgebrochen ist, und sieh, wo er heute Nacht steht.',
    posterCta: 'Oder mach kostenlos ein Poster vom echten Himmel jener Nacht, mit dem Mond in seiner Phase.',
    findStar: 'Finde deinen Stern',
    makePoster: 'Poster erstellen',
    prev: 'Zurück',
    next: 'Weiter',
    allYears: 'Alle Jahre',

    bornHubTitle: 'Der Stern deines Geburtsjahres: das Licht, das damals aufbrach, kommt jetzt an | Sky of Your Day',
    bornHubDescription: 'Für jedes Geburtsjahr seit 1930 die Sterne, deren Licht in jenem Jahr aufgebrochen ist und jetzt die Erde erreicht. Finde deinen.',
    bornHubH1: 'Der Stern deines Geburtsjahres',
    bornHubLead: 'Das Licht eines Sterns in 40 Lichtjahren Entfernung ist vor 40 Jahren aufgebrochen. Jedes Geburtsjahr hat also seine Sterne: die, deren Licht damals aufbrach und jetzt ankommt.',
    bornTitle: (y: number) => `Geboren ${y}? Der Stern, dessen Licht in deinem Geburtsjahr aufbrach | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `Licht, das ${y} aufgebrochen ist, erreicht die Erde jetzt von Sternen in etwa ${ly} Lichtjahren Entfernung, wie ${star}. Der Stern für jeden Monat ${y} und wo du ihn findest.`,
    bornH1: (y: number) => `Geboren ${y}: dein Stern`,
    bornLead: (y: number, ly: string) =>
      `Licht, das ${y} aufgebrochen ist, erreicht die Erde genau jetzt von Sternen in etwa ${ly} Lichtjahren Entfernung. Hier ist der Stern für jeden Monat ${y}: der, dessen Licht damals aufbrach und ungefähr heute ankommt.`,
    colStar: 'Stern',
    colDistance: 'Entfernung',
    colSeen: 'So siehst du ihn',
    colConstellation: 'Sternbild',
    lightYears: (n: string) => `${n} Lichtjahre`,
    exactDate: 'Für den genauen Stern deines Geburtstags, und um zu wissen, wo du ihn heute Nacht siehst:',
    moonOfYear: (y: number) => `Der Mond ${y}`,

    starsHubTitle: 'Sterne mit Namen: wo man sie findet, Entfernung und Wissenswertes | Sky of Your Day',
    starsHubDescription: 'Alle Sterne mit offiziellem Namen: wo sie am Himmel stehen, wie weit sie entfernt sind, wann man sie sieht und wann das Licht aufbrach, das du heute Nacht siehst.',
    starsHubH1: 'Sterne mit Namen',
    starsHubLead: 'Die Internationale Astronomische Union hat einigen hundert Sternen offizielle Namen gegeben. Für jeden: wo du ihn findest, wie weit er entfernt ist und wann das Licht aufbrach, das du heute Nacht siehst.',
    brightestHeading: 'Die hellsten',
    allHeading: 'Alle Sterne mit Namen',

    starTitle: (name: string) => `${name}: wo man ihn findet, Entfernung und Wissenswertes | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} ist ${kind}${dist}. Wo du ihn am Himmel findest, wann er zu sehen ist und wie hell er ist.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, ${ly} Lichtjahre entfernt: das Licht, das du heute Nacht siehst, brach um ${year} auf` : `, ${ly} Lichtjahre entfernt`),
    whereHeading: 'Wo du ihn findest',
    factsHeading: 'Wie er ist',
    lightLeft: (year: number) => `Das Licht, das du heute Nacht von ihm siehst, ist um ${year} aufgebrochen.`,
    lightLeftAncient: (years: string) => `Das Licht, das du heute Nacht von ihm siehst, ist vor etwa ${years} Jahren aufgebrochen.`,
    unknownDistance: 'Seine Entfernung ist nicht genau bekannt.',
    fromLatitudes: 'Von Mitteleuropa aus, etwa von Berlin, Wien oder Zürich,',
    bestMonths: (list: string) => `ist er am besten am Abendhimmel im ${list} zu sehen.`,
    circumpolar: 'geht er nie unter: er kreist die ganze Nacht und das ganze Jahr um den Pol.',
    neverVisible: 'geht er nie auf: er gehört zum Südhimmel.',
    lowAlways: 'bleibt er immer tief über dem Südhorizont.',
    birthYearLink: (year: number) => `Er ist der Stern aller, die um ${year} geboren sind: das Licht, das damals aufbrach, erreicht jetzt die Erde.`,
    sameConstellation: (con: string) => `Weitere Sterne mit Namen im Sternbild ${con}`,
    magnitude: (m: string) => `Scheinbare Helligkeit ${m} mag.`,
  },
  fr: {
    phase: {
      new: 'Nouvelle lune', waxingCrescent: 'Premier croissant', firstQuarter: 'Premier quartier', waxingGibbous: 'Gibbeuse croissante',
      full: 'Pleine lune', waningGibbous: 'Gibbeuse décroissante', lastQuarter: 'Dernier quartier', waningCrescent: 'Dernier croissant',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    timeZoneNote: 'Les heures sont à l’heure de Paris, avec l’heure d’été quand elle était en vigueur.',
    moonTz: 'Europe/Paris',
    visibilityLat: 47,

    moonHubTitle: 'Quelle lune le jour de ta naissance ? Phases de la Lune à toute date | Sky of Your Day',
    moonHubDescription: 'La phase de la Lune à n’importe quelle date depuis 1930 : pleines lunes, nouvelles lunes et calendrier lunaire de chaque mois, avec les heures exactes.',
    moonHubH1: 'Quelle lune y avait-il le jour de ta naissance ?',
    moonHubLead: 'Choisis une date pour voir la phase de la Lune ce jour-là, quelle part était éclairée et quand sont tombées la pleine lune et la nouvelle lune les plus proches. Chaque mois depuis 1930 a son calendrier.',
    lookUp: 'Voir la Lune',
    dateLabel: 'Date',
    yearsHeading: 'Par année',

    moonYearTitle: (y: number) => `Phases de la Lune ${y} : toutes les pleines lunes et nouvelles lunes | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Les ${fulls} pleines lunes et toutes les nouvelles lunes de ${y}, avec date et heure, et le calendrier lunaire jour par jour de chaque mois.`,
    moonYearH1: (y: number) => `Phases de la Lune en ${y}`,
    moonYearLead: (y: number, fulls: number) => `En ${y}, il y a eu ${fulls} pleines lunes. Choisis un mois pour voir la phase de la Lune jour par jour.`,
    blueMoon: (month: string) => `En ${month}, il y a eu deux pleines lunes : la seconde est ce qu’on appelle une « lune bleue ».`,
    colMonth: 'Mois',
    colFull: 'Pleine lune',
    colNew: 'Nouvelle lune',

    moonMonthTitle: (m: string, y: number) => `Phases de la Lune ${m} ${y} : pleine lune, nouvelle lune et calendrier | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Pleine lune le ${full}. ` : ''}${nw ? `Nouvelle lune le ${nw}. ` : ''}La phase de la Lune et la part éclairée chaque jour de ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Phases de la Lune en ${m} ${y}`,
    keyMoments: 'Les phases principales',
    litShare: (p: number) => `éclairée à ${p} %`,
    at: (date: string, time: string) => `${date} à ${time}`,
    bornThisMonth: 'Ta naissance est de ce mois-ci ?',
    bornCta: 'Découvre l’étoile dont la lumière est partie le jour de ta naissance, et où elle se trouve ce soir.',
    posterCta: 'Ou crée gratuitement le poster du vrai ciel de cette nuit-là, avec la Lune dans sa phase.',
    findStar: 'Trouve ton étoile',
    makePoster: 'Créer le poster',
    prev: 'Précédent',
    next: 'Suivant',
    allYears: 'Toutes les années',

    bornHubTitle: 'L’étoile de ton année de naissance : la lumière partie cette année-là arrive maintenant | Sky of Your Day',
    bornHubDescription: 'Pour chaque année de naissance depuis 1930, les étoiles dont la lumière est partie cette année-là et atteint la Terre maintenant. Trouve la tienne.',
    bornHubH1: 'L’étoile de ton année de naissance',
    bornHubLead: 'La lumière d’une étoile à 40 années-lumière est partie il y a 40 ans. Chaque année de naissance a donc ses étoiles : celles dont la lumière est partie alors et arrive maintenant.',
    bornTitle: (y: number) => `Né en ${y} ? L’étoile dont la lumière est partie ton année de naissance | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `La lumière partie en ${y} atteint la Terre maintenant depuis des étoiles situées à environ ${ly} années-lumière, comme ${star}. L’étoile de chaque mois de ${y} et où la trouver.`,
    bornH1: (y: number) => `Nés en ${y} : votre étoile`,
    bornLead: (y: number, ly: string) =>
      `La lumière partie en ${y} atteint la Terre en ce moment depuis des étoiles situées à environ ${ly} années-lumière. Voici l’étoile de chaque mois de ${y} : celle dont la lumière est partie alors et arrive à peu près aujourd’hui.`,
    colStar: 'Étoile',
    colDistance: 'Distance',
    colSeen: 'Comment la voir',
    colConstellation: 'Constellation',
    lightYears: (n: string) => `${n} années-lumière`,
    exactDate: 'Pour l’étoile exacte de ton anniversaire, et pour savoir où la regarder ce soir :',
    moonOfYear: (y: number) => `La Lune en ${y}`,

    starsHubTitle: 'Les étoiles qui ont un nom : où les trouver, distance et curiosités | Sky of Your Day',
    starsHubDescription: 'Toutes les étoiles qui ont un nom officiel : où elles sont dans le ciel, à quelle distance, quand on les voit et quand est partie la lumière que tu vois ce soir.',
    starsHubH1: 'Les étoiles qui ont un nom',
    starsHubLead: 'L’Union astronomique internationale a donné un nom officiel à quelques centaines d’étoiles. Pour chacune : où la trouver, à quelle distance elle est et quand est partie la lumière que tu vois ce soir.',
    brightestHeading: 'Les plus brillantes',
    allHeading: 'Toutes les étoiles qui ont un nom',

    starTitle: (name: string) => `${name} : où la trouver, distance et curiosités | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} est ${kind}${dist}. Où la trouver dans le ciel, quand on la voit et à quel point elle brille.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, à ${ly} années-lumière : la lumière que tu vois ce soir est partie vers ${year}` : `, à ${ly} années-lumière`),
    whereHeading: 'Où la trouver',
    factsHeading: 'Comment elle est',
    lightLeft: (year: number) => `La lumière que tu vois d’elle ce soir est partie vers ${year}.`,
    lightLeftAncient: (years: string) => `La lumière que tu vois d’elle ce soir est partie il y a environ ${years} ans.`,
    unknownDistance: 'Sa distance n’est pas connue avec précision.',
    fromLatitudes: 'Depuis la France, la Belgique ou la Suisse,',
    bestMonths: (list: string) => `elle se voit le mieux le soir en ${list}.`,
    circumpolar: 'elle ne se couche jamais : elle tourne autour du pôle toute la nuit, toute l’année.',
    neverVisible: 'elle ne se lève jamais : elle appartient au ciel austral.',
    lowAlways: 'elle reste toujours basse sur l’horizon sud.',
    birthYearLink: (year: number) => `C’est l’étoile des personnes nées vers ${year} : la lumière partie alors atteint la Terre maintenant.`,
    sameConstellation: (con: string) => `Autres étoiles qui ont un nom dans la constellation ${con}`,
    magnitude: (m: string) => `Magnitude apparente ${m}.`,
  },
  pt: {
    phase: {
      new: 'Lua nova', waxingCrescent: 'Lua crescente', firstQuarter: 'Quarto crescente', waxingGibbous: 'Crescente gibosa',
      full: 'Lua cheia', waningGibbous: 'Minguante gibosa', lastQuarter: 'Quarto minguante', waningCrescent: 'Lua minguante',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    timeZoneNote: 'Os horários estão no horário de Brasília, com horário de verão quando estava em vigor.',
    moonTz: 'America/Sao_Paulo',
    visibilityLat: -23,

    moonHubTitle: 'Qual era a lua no dia em que você nasceu? Fases da Lua de qualquer data | Sky of Your Day',
    moonHubDescription: 'Veja a fase da Lua em qualquer data desde 1930: luas cheias, luas novas e o calendário lunar de cada mês, com os horários exatos.',
    moonHubH1: 'Qual era a lua no dia do seu nascimento?',
    moonHubLead: 'Escolha uma data para ver a fase da Lua naquele dia, quanto dela estava iluminado e quando caíram a lua cheia e a lua nova mais próximas. Cada mês desde 1930 tem seu calendário.',
    lookUp: 'Ver a Lua',
    dateLabel: 'Data',
    yearsHeading: 'Por ano',

    moonYearTitle: (y: number) => `Fases da Lua ${y}: todas as luas cheias e luas novas | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `As ${fulls} luas cheias e todas as luas novas de ${y}, com data e hora, e o calendário lunar dia a dia de cada mês.`,
    moonYearH1: (y: number) => `Fases da Lua em ${y}`,
    moonYearLead: (y: number, fulls: number) => `Em ${y} houve ${fulls} luas cheias. Escolha um mês para ver a fase da Lua dia a dia.`,
    blueMoon: (month: string) => `Em ${month} houve duas luas cheias: a segunda é o que se chama “lua azul”.`,
    colMonth: 'Mês',
    colFull: 'Lua cheia',
    colNew: 'Lua nova',

    moonMonthTitle: (m: string, y: number) => `Fases da Lua ${m} ${y}: lua cheia, lua nova e calendário | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Lua cheia em ${full}. ` : ''}${nw ? `Lua nova em ${nw}. ` : ''}A fase da Lua e quanto dela estava iluminado em cada dia de ${m} de ${y}.`,
    moonMonthH1: (m: string, y: number) => `Fases da Lua em ${m} de ${y}`,
    keyMoments: 'As fases principais',
    litShare: (p: number) => `${p}% iluminada`,
    at: (date: string, time: string) => `${date} às ${time}`,
    bornThisMonth: 'Nasceu neste mês?',
    bornCta: 'Descubra a estrela cuja luz partiu no dia do seu nascimento e onde ela está esta noite.',
    posterCta: 'Ou crie de graça o pôster do céu real daquela noite, com a Lua na sua fase.',
    findStar: 'Encontre sua estrela',
    makePoster: 'Criar o pôster',
    prev: 'Anterior',
    next: 'Próximo',
    allYears: 'Todos os anos',

    bornHubTitle: 'A estrela do seu ano de nascimento: a luz que partiu naquele ano chega agora | Sky of Your Day',
    bornHubDescription: 'Para cada ano de nascimento desde 1930, as estrelas cuja luz partiu naquele ano e está chegando agora à Terra. Encontre a sua.',
    bornHubH1: 'A estrela do seu ano de nascimento',
    bornHubLead: 'A luz de uma estrela a 40 anos-luz partiu há 40 anos. Então cada ano de nascimento tem as suas estrelas: aquelas cuja luz partiu naquela época e está chegando agora.',
    bornTitle: (y: number) => `Nascidos em ${y}: a estrela cuja luz partiu naquele ano | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `A luz que partiu em ${y} está chegando agora à Terra de estrelas a cerca de ${ly} anos-luz, como ${star}. A estrela de cada mês de ${y} e onde encontrá-la.`,
    bornH1: (y: number) => `Nascidos em ${y}: a sua estrela`,
    bornLead: (y: number, ly: string) =>
      `A luz que partiu em ${y} está chegando à Terra agora mesmo de estrelas a cerca de ${ly} anos-luz. Esta é a estrela de cada mês de ${y}: aquela cuja luz partiu naquela época e chega mais ou menos hoje.`,
    colStar: 'Estrela',
    colDistance: 'Distância',
    colSeen: 'Como ver',
    colConstellation: 'Constelação',
    lightYears: (n: string) => `${n} anos-luz`,
    exactDate: 'Para a estrela exata do seu aniversário, e para saber onde olhar esta noite:',
    moonOfYear: (y: number) => `A Lua em ${y}`,

    starsHubTitle: 'As estrelas com nome: onde encontrá-las, distância e curiosidades | Sky of Your Day',
    starsHubDescription: 'Todas as estrelas com nome oficial: onde estão no céu, a que distância, quando podem ser vistas e quando partiu a luz que você vê esta noite.',
    starsHubH1: 'As estrelas com nome',
    starsHubLead: 'A União Astronômica Internacional deu nome oficial a algumas centenas de estrelas. Para cada uma: onde encontrá-la, a que distância está e quando partiu a luz que você vê esta noite.',
    brightestHeading: 'As mais brilhantes',
    allHeading: 'Todas as estrelas com nome',

    starTitle: (name: string) => `${name}: onde encontrá-la, distância e curiosidades | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} é ${kind}${dist}. Onde encontrá-la no céu, quando ela pode ser vista e quanto ela brilha.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, a ${ly} anos-luz: a luz que você vê esta noite partiu por volta de ${year}` : `, a ${ly} anos-luz`),
    whereHeading: 'Onde encontrá-la',
    factsHeading: 'Como ela é',
    lightLeft: (year: number) => `A luz que você vê dela esta noite partiu por volta de ${year}.`,
    lightLeftAncient: (years: string) => `A luz que você vê dela esta noite partiu há cerca de ${years} anos.`,
    unknownDistance: 'A distância dela não é conhecida com precisão.',
    fromLatitudes: 'De boa parte do Brasil, como São Paulo ou Rio de Janeiro,',
    bestMonths: (list: string) => `ela é vista melhor à noite em ${list}.`,
    circumpolar: 'ela nunca se põe: gira em torno do polo sul a noite toda, o ano todo.',
    neverVisible: 'ela nunca nasce: pertence ao céu do hemisfério norte.',
    lowAlways: 'ela fica sempre baixa sobre o horizonte norte.',
    birthYearLink: (year: number) => `É a estrela de quem nasceu por volta de ${year}: a luz que partiu naquela época está chegando agora à Terra.`,
    sameConstellation: (con: string) => `Outras estrelas com nome na constelação ${con}`,
    magnitude: (m: string) => `Magnitude aparente ${m}.`,
  },
} satisfies Record<Lang, unknown>;

export type PageText = (typeof PT)['en'];

export function monthName(lang: Lang, month: number): string {
  return new Date(Date.UTC(2000, month - 1, 1)).toLocaleDateString(lang, { month: 'long', timeZone: 'UTC' });
}
