import type { Lang } from './i18n.svelte';
import type { PhaseKey } from './moon';

/** Copy for the generated pages (moon phases, birth years, star pages). */
export const PT = {
  en: {
    phase: {
      new: 'New Moon', waxingCrescent: 'Waxing crescent', firstQuarter: 'First quarter', waxingGibbous: 'Waxing gibbous',
      full: 'Full Moon', waningGibbous: 'Waning gibbous', lastQuarter: 'Last quarter', waningCrescent: 'Waning crescent',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    timeZoneNote: 'Times are in UTC (Greenwich).',
    moonTz: 'UTC',

    moonHubTitle: 'Moon Phase on Any Date: What Was the Moon the Day You Were Born? | Sky of Your Day',
    moonHubDescription: 'Look up the Moon’s phase on any date since 1930: full moons, new moons and a daily calendar for every month, with exact times.',
    moonHubH1: 'What was the Moon like on the day you were born?',
    moonHubLead: 'Pick a date to see the Moon’s phase that day, how much of it was lit, and when the nearest full and new moons fell. Every month since 1930 has its own calendar.',
    lookUp: 'Show the Moon',
    dateLabel: 'Date',
    yearsHeading: 'Browse by year',

    moonYearTitle: (y: number) => `Moon Phases ${y}: Every Full Moon and New Moon | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `All ${fulls} full moons and every new moon of ${y}, with dates and times, and a daily Moon calendar for each month.`,
    moonYearH1: (y: number) => `Moon phases in ${y}`,
    moonYearLead: (y: number, fulls: number) => `There were ${fulls} full moons in ${y}. Choose a month for the Moon’s phase on every day.`,
    blueMoon: (month: string) => `${month} had two full moons: the second is what is called a blue moon.`,
    colMonth: 'Month',
    colFull: 'Full Moon',
    colNew: 'New Moon',

    moonMonthTitle: (m: string, y: number) => `Moon Phases ${m} ${y}: Full Moon, New Moon & Daily Calendar | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Full Moon on ${full}. ` : ''}${nw ? `New Moon on ${nw}. ` : ''}The Moon’s phase and how much of it was lit on every day of ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Moon phases in ${m} ${y}`,
    keyMoments: 'Main phases',
    litShare: (p: number) => `${p}% lit`,
    at: (date: string, time: string) => `${date} at ${time}`,
    bornThisMonth: 'Born this month?',
    bornCta: 'Find the star whose light left it the day you were born, and see where it is tonight.',
    posterCta: 'Or make a free poster of the real sky of that night, with the Moon in its phase.',
    findStar: 'Find your star',
    makePoster: 'Make the poster',
    prev: 'Previous',
    next: 'Next',
    allYears: 'All years',

    bornHubTitle: 'The Star of Your Birth Year: Whose Light Left the Year You Were Born | Sky of Your Day',
    bornHubDescription: 'For every birth year since 1930, the stars whose light set out that year and is reaching Earth now. Find yours.',
    bornHubH1: 'The star of your birth year',
    bornHubLead: 'Light from a star 40 light years away set out 40 years ago. So every birth year has its stars: the ones whose light left them that year and is arriving now.',
    bornTitle: (y: number) => `Born in ${y}? The Star Whose Light Left the Year You Were Born | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `Light that set out in ${y} is reaching Earth now from stars about ${ly} light years away, like ${star}. See the star for each month of ${y} and where to find it.`,
    bornH1: (y: number) => `Born in ${y}: your star`,
    bornLead: (y: number, ly: string) =>
      `Light that set out in ${y} is reaching Earth right now from stars about ${ly} light years away. Here is the star for each month of ${y}: the one whose light left it then and is arriving about now.`,
    colStar: 'Star',
    colDistance: 'Distance',
    colSeen: 'How to see it',
    colConstellation: 'Constellation',
    lightYears: (n: string) => `${n} light years`,
    exactDate: 'For the exact star of your birthday, and where to look for it tonight:',
    moonOfYear: (y: number) => `The Moon in ${y}`,

    starsHubTitle: 'Named Stars: Where to Find Them, Distance and Facts | Sky of Your Day',
    starsHubDescription: 'Every star with an official name: where it is in the sky, how far away, when you can see it and when the light you see tonight left it.',
    starsHubH1: 'Stars with a name',
    starsHubLead: 'The International Astronomical Union has given official names to a few hundred stars. For each: where to find it, how far away it is, and when the light you see tonight set out.',
    brightestHeading: 'The brightest',
    allHeading: 'All named stars',

    starTitle: (name: string) => `${name}: Where to Find It, Distance and Facts | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} is ${kind}${dist}. Where to find it in the sky, when you can see it and how bright it is.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, ${ly} light years away: the light you see tonight left it around ${year}` : `, ${ly} light years away`),
    whereHeading: 'Where to find it',
    factsHeading: 'What it’s like',
    lightLeft: (year: number) => `The light you see from it tonight left it around ${year}.`,
    lightLeftAncient: (years: string) => `The light you see from it tonight set out about ${years} years ago.`,
    unknownDistance: 'Its distance is not known precisely.',
    fromLatitudes: 'From mid-northern latitudes, such as New York, Rome or Tokyo,',
    bestMonths: (list: string) => `it is best seen in the evening sky in ${list}.`,
    circumpolar: 'it never sets: it circles the pole all night, all year.',
    neverVisible: 'it never rises: it belongs to the southern sky.',
    lowAlways: 'it only ever stays low over the southern horizon.',
    birthYearLink: (year: number) => `It is the star of people born around ${year}: the light that left it then is reaching Earth now.`,
    sameConstellation: (con: string) => `Other named stars in ${con}`,
    magnitude: (m: string) => `Apparent magnitude ${m}.`,
  },
  es: {
    phase: {
      new: 'Luna nueva', waxingCrescent: 'Luna creciente', firstQuarter: 'Cuarto creciente', waxingGibbous: 'Gibosa creciente',
      full: 'Luna llena', waningGibbous: 'Gibosa menguante', lastQuarter: 'Cuarto menguante', waningCrescent: 'Luna menguante',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    timeZoneNote: 'Las horas están en UTC (hora universal).',
    moonTz: 'UTC',

    moonHubTitle: '¿Qué luna había el día que naciste? Fases lunares de cualquier fecha | Sky of Your Day',
    moonHubDescription: 'Consulta la fase de la Luna en cualquier fecha desde 1930: lunas llenas, lunas nuevas y el calendario lunar de cada mes, con las horas exactas.',
    moonHubH1: '¿Qué luna había el día de tu nacimiento?',
    moonHubLead: 'Elige una fecha para ver la fase de la Luna ese día, qué parte estaba iluminada y cuándo cayeron la luna llena y la luna nueva más cercanas. Cada mes desde 1930 tiene su calendario.',
    lookUp: 'Ver la Luna',
    dateLabel: 'Fecha',
    yearsHeading: 'Por años',

    moonYearTitle: (y: number) => `Fases lunares ${y}: todas las lunas llenas y lunas nuevas | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Las ${fulls} lunas llenas y todas las lunas nuevas de ${y}, con fecha y hora, y el calendario lunar día a día de cada mes.`,
    moonYearH1: (y: number) => `Fases lunares de ${y}`,
    moonYearLead: (y: number, fulls: number) => `En ${y} hubo ${fulls} lunas llenas. Elige un mes para ver la fase de la Luna día a día.`,
    blueMoon: (month: string) => `En ${month} hubo dos lunas llenas: la segunda es la que se llama “luna azul”.`,
    colMonth: 'Mes',
    colFull: 'Luna llena',
    colNew: 'Luna nueva',

    moonMonthTitle: (m: string, y: number) => `Fases lunares ${m} ${y}: luna llena, luna nueva y calendario | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Luna llena el ${full}. ` : ''}${nw ? `Luna nueva el ${nw}. ` : ''}La fase de la Luna y qué parte estaba iluminada cada día de ${m} de ${y}.`,
    moonMonthH1: (m: string, y: number) => `Fases lunares de ${m} de ${y}`,
    keyMoments: 'Las fases principales',
    litShare: (p: number) => `iluminada al ${p}%`,
    at: (date: string, time: string) => `${date} a las ${time}`,
    bornThisMonth: '¿Tu nacimiento es de este mes?',
    bornCta: 'Descubre la estrella cuya luz salió el día de tu nacimiento y dónde está esta noche.',
    posterCta: 'O crea gratis el póster del cielo real de aquella noche, con la Luna en su fase.',
    findStar: 'Encuentra tu estrella',
    makePoster: 'Crear el póster',
    prev: 'Anterior',
    next: 'Siguiente',
    allYears: 'Todos los años',

    bornHubTitle: 'La estrella de tu año de nacimiento: la luz que salió ese año llega ahora | Sky of Your Day',
    bornHubDescription: 'Para cada año de nacimiento desde 1930, las estrellas cuya luz salió ese año y está llegando ahora a la Tierra. Encuentra la tuya.',
    bornHubH1: 'La estrella de tu año de nacimiento',
    bornHubLead: 'La luz de una estrella a 40 años luz salió hace 40 años. Así que cada año de nacimiento tiene sus estrellas: aquellas cuya luz salió entonces y está llegando ahora.',
    bornTitle: (y: number) => `Nacidos en ${y}: la estrella cuya luz salió ese año | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `La luz que salió en ${y} está llegando ahora a la Tierra desde estrellas a unos ${ly} años luz, como ${star}. La estrella de cada mes de ${y} y dónde encontrarla.`,
    bornH1: (y: number) => `Nacidos en ${y}: vuestra estrella`,
    bornLead: (y: number, ly: string) =>
      `La luz que salió en ${y} está llegando a la Tierra justo ahora desde estrellas a unos ${ly} años luz. Esta es la estrella de cada mes de ${y}: aquella cuya luz salió entonces y llega más o menos hoy.`,
    colStar: 'Estrella',
    colDistance: 'Distancia',
    colSeen: 'Cómo verla',
    colConstellation: 'Constelación',
    lightYears: (n: string) => `${n} años luz`,
    exactDate: 'Para la estrella exacta de tu cumpleaños, y para saber dónde mirarla esta noche:',
    moonOfYear: (y: number) => `La Luna en ${y}`,

    starsHubTitle: 'Las estrellas con nombre: dónde encontrarlas, distancia y curiosidades | Sky of Your Day',
    starsHubDescription: 'Todas las estrellas con nombre oficial: dónde están en el cielo, a qué distancia, cuándo se ven y cuándo salió la luz que ves esta noche.',
    starsHubH1: 'Las estrellas con nombre',
    starsHubLead: 'La Unión Astronómica Internacional ha dado nombre oficial a unos cientos de estrellas. Para cada una: dónde encontrarla, a qué distancia está y cuándo salió la luz que ves esta noche.',
    brightestHeading: 'Las más brillantes',
    allHeading: 'Todas las estrellas con nombre',

    starTitle: (name: string) => `${name}: dónde encontrarla, distancia y curiosidades | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} es ${kind}${dist}. Dónde encontrarla en el cielo, cuándo se ve y cuánto brilla.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, a ${ly} años luz: la luz que ves esta noche salió hacia ${year}` : `, a ${ly} años luz`),
    whereHeading: 'Dónde encontrarla',
    factsHeading: 'Cómo es',
    lightLeft: (year: number) => `La luz que ves de ella esta noche salió hacia ${year}.`,
    lightLeftAncient: (years: string) => `La luz que ves de ella esta noche salió hace unos ${years} años.`,
    unknownDistance: 'Su distancia no se conoce con precisión.',
    fromLatitudes: 'Desde latitudes medias del norte, como Madrid, Ciudad de México o Nueva York,',
    bestMonths: (list: string) => `se ve mejor al anochecer en ${list}.`,
    circumpolar: 'nunca se pone: gira alrededor del polo toda la noche, todo el año.',
    neverVisible: 'nunca sale: pertenece al cielo austral.',
    lowAlways: 'siempre se queda baja sobre el horizonte sur.',
    birthYearLink: (year: number) => `Es la estrella de los nacidos hacia ${year}: la luz que salió entonces está llegando ahora a la Tierra.`,
    sameConstellation: (con: string) => `Otras estrellas con nombre en la constelación ${con}`,
    magnitude: (m: string) => `Magnitud aparente ${m}.`,
  },
  it: {
    phase: {
      new: 'Luna nuova', waxingCrescent: 'Luna crescente', firstQuarter: 'Primo quarto', waxingGibbous: 'Gibbosa crescente',
      full: 'Luna piena', waningGibbous: 'Gibbosa calante', lastQuarter: 'Ultimo quarto', waningCrescent: 'Luna calante',
    } satisfies Record<PhaseKey, string>,
    weekdays: ['Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'],
    timeZoneNote: 'Gli orari sono in ora italiana, con l’ora legale quando era in vigore.',
    moonTz: 'Europe/Rome',

    moonHubTitle: 'Che luna c’era il giorno della tua nascita? Fasi lunari di ogni data | Sky of Your Day',
    moonHubDescription: 'Scopri la fase della Luna in qualsiasi data dal 1930: lune piene, lune nuove e calendario lunare di ogni mese, con gli orari esatti.',
    moonHubH1: 'Che luna c’era il giorno della tua nascita?',
    moonHubLead: 'Scegli una data per vedere la fase della Luna quel giorno, quanta parte era illuminata e quando sono cadute la luna piena e la luna nuova più vicine. Ogni mese dal 1930 ha il suo calendario.',
    lookUp: 'Mostra la Luna',
    dateLabel: 'Data',
    yearsHeading: 'Sfoglia per anno',

    moonYearTitle: (y: number) => `Fasi lunari ${y}: tutte le lune piene e le lune nuove | Sky of Your Day`,
    moonYearDescription: (y: number, fulls: number) => `Le ${fulls} lune piene e tutte le lune nuove del ${y}, con data e ora, e il calendario lunare giorno per giorno di ogni mese.`,
    moonYearH1: (y: number) => `Fasi lunari del ${y}`,
    moonYearLead: (y: number, fulls: number) => `Nel ${y} ci sono state ${fulls} lune piene. Scegli un mese per vedere la fase della Luna giorno per giorno.`,
    blueMoon: (month: string) => `A ${month} ci sono state due lune piene: la seconda è quella che si chiama “luna blu”.`,
    colMonth: 'Mese',
    colFull: 'Luna piena',
    colNew: 'Luna nuova',

    moonMonthTitle: (m: string, y: number) => `Fasi lunari ${m} ${y}: luna piena, luna nuova e calendario | Sky of Your Day`,
    moonMonthDescription: (m: string, y: number, full: string, nw: string) =>
      `${full ? `Luna piena il ${full}. ` : ''}${nw ? `Luna nuova il ${nw}. ` : ''}La fase della Luna e quanta parte era illuminata in ogni giorno di ${m} ${y}.`,
    moonMonthH1: (m: string, y: number) => `Fasi lunari di ${m} ${y}`,
    keyMoments: 'Le fasi principali',
    litShare: (p: number) => `illuminata al ${p}%`,
    at: (date: string, time: string) => `${date} alle ${time}`,
    bornThisMonth: 'La tua nascita è di questo mese?',
    bornCta: 'Scopri la stella la cui luce è partita il giorno della tua nascita e dove si trova stasera.',
    posterCta: 'Oppure crea gratis il poster del cielo vero di quella notte, con la Luna nella sua fase.',
    findStar: 'Trova la tua stella',
    makePoster: 'Crea il poster',
    prev: 'Precedente',
    next: 'Successivo',
    allYears: 'Tutti gli anni',

    bornHubTitle: 'La stella del tuo anno di nascita: la luce partita quell’anno arriva adesso | Sky of Your Day',
    bornHubDescription: 'Per ogni anno di nascita dal 1930, le stelle la cui luce è partita quell’anno e arriva sulla Terra adesso. Trova la tua.',
    bornHubH1: 'La stella del tuo anno di nascita',
    bornHubLead: 'La luce di una stella lontana 40 anni luce è partita 40 anni fa. Ogni anno di nascita ha quindi le sue stelle: quelle la cui luce è partita allora e arriva adesso.',
    bornTitle: (y: number) => `Nati nel ${y}: la stella la cui luce è partita quell’anno | Sky of Your Day`,
    bornDescription: (y: number, star: string, ly: string) =>
      `La luce partita nel ${y} arriva sulla Terra adesso da stelle lontane circa ${ly} anni luce, come ${star}. La stella di ogni mese del ${y} e dove trovarla.`,
    bornH1: (y: number) => `Nati nel ${y}: la vostra stella`,
    bornLead: (y: number, ly: string) =>
      `La luce partita nel ${y} arriva sulla Terra proprio adesso da stelle lontane circa ${ly} anni luce. Ecco la stella di ogni mese del ${y}: quella la cui luce è partita allora e arriva più o meno oggi.`,
    colStar: 'Stella',
    colDistance: 'Distanza',
    colSeen: 'Come vederla',
    colConstellation: 'Costellazione',
    lightYears: (n: string) => `${n} anni luce`,
    exactDate: 'Per la stella esatta del tuo compleanno, e per sapere dove guardarla stasera:',
    moonOfYear: (y: number) => `La Luna nel ${y}`,

    starsHubTitle: 'Le stelle con un nome: dove trovarle, distanza e curiosità | Sky of Your Day',
    starsHubDescription: 'Tutte le stelle con un nome ufficiale: dove si trovano in cielo, quanto distano, quando si vedono e quando è partita la luce che vedi stasera.',
    starsHubH1: 'Le stelle con un nome',
    starsHubLead: 'L’Unione Astronomica Internazionale ha dato un nome ufficiale ad alcune centinaia di stelle. Per ognuna: dove trovarla, quanto dista e quando è partita la luce che vedi stasera.',
    brightestHeading: 'Le più luminose',
    allHeading: 'Tutte le stelle con un nome',

    starTitle: (name: string) => `${name}: dove si trova, distanza e curiosità | Sky of Your Day`,
    starDescription: (name: string, kind: string, dist: string) => `${name} è ${kind}${dist}. Dove trovarla in cielo, quando si vede e quanto è luminosa.`,
    distanceShort: (ly: string, year: number | null) => (year ? `, a ${ly} anni luce: la luce che vedi stasera è partita intorno al ${year}` : `, a ${ly} anni luce`),
    whereHeading: 'Dove trovarla',
    factsHeading: 'Com’è fatta',
    lightLeft: (year: number) => `La luce che vedi stasera è partita da lei intorno al ${year}.`,
    lightLeftAncient: (years: string) => `La luce che vedi stasera è partita da lei circa ${years} anni fa.`,
    unknownDistance: 'La sua distanza non è nota con precisione.',
    fromLatitudes: 'Dall’Italia',
    bestMonths: (list: string) => `si vede meglio la sera nei mesi di ${list}.`,
    circumpolar: 'non tramonta mai: gira intorno al polo tutta la notte, tutto l’anno.',
    neverVisible: 'non sorge mai: appartiene al cielo australe.',
    lowAlways: 'resta sempre bassa sull’orizzonte sud.',
    birthYearLink: (year: number) => `È la stella dei nati intorno al ${year}: la luce partita allora arriva sulla Terra adesso.`,
    sameConstellation: (con: string) => `Altre stelle con un nome nella costellazione ${con}`,
    magnitude: (m: string) => `Magnitudine apparente ${m}.`,
  },
} satisfies Record<Lang, unknown>;

export type PageText = (typeof PT)['en'];

export function monthName(lang: Lang, month: number): string {
  return new Date(Date.UTC(2000, month - 1, 1)).toLocaleDateString(lang, { month: 'long', timeZone: 'UTC' });
}
